#define VIAL_KEYBOARD_UID {0xD8, 0xFA, 0x1B, 0xE3, 0x84, 0x41, 0x9F, 0x78}

#define LOCKING_SUPPORT_ENABLE


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 0
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
