
#define VIAL_KEYBOARD_UID {0xF6, 0xF7, 0x43, 0xDB, 0x22, 0x01, 0x16, 0xD9}

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 2
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2

#define CAPSENSE_KEYBOARD_SETTLE_TIME_US 8
#define CAPSENSE_DAC_SETTLE_TIME_US 8
#define CAPSENSE_HARDCODED_SAMPLE_TIME 3

#define CAPSENSE_CAL_ENABLED 1
#define CAPSENSE_CAL_DEBUG 1
#define CAPSENSE_CAL_INIT_REPS 16
#define CAPSENSE_CAL_EACHKEY_REPS 16
#define CAPSENSE_CAL_BINS 7
#define CAPSENSE_CAL_THRESHOLD_OFFSET 50
